# Apache 2.x configuration
# Vagrant/Ansible Lamp Stack
# Nathan Dentzau <nathan.dentzau@gmail.com>

- name: Install apache 2.x
  apt: pkg=apache2 state=latest

- name: Set the apache site configuration file
  template: src=apache.conf.tpl
            dest=/etc/apache2/sites-available/000-default.conf

- name: Restart apache
  service: name=apache2
           enabled=yes
           state=restarted
